FORMAT: 1A
HOST: https://tournament.apiblueprint.org/

# Tournament

Tournament is a simple API allowing consumers to view tournaments and vote in them.

## Tournaments Collection [/tournaments]

### List All Tournaments [GET]

+ Response 200 (application/json)

        [
            {
                "Tournament": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Tournament [POST]

You may create your own Tournament using this action. It takes a JSON
object containing a tournament and a collection of tournaments in the
form of choices.

+ Request (application/json)

        {
            "Tournament": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /tournament/2

    + Body

            {
                "Tournaments": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
