FORMAT: 1A
HOST: https://champion.apiblueprint.org/

# Champion

Champion is a simple API allowing consumers to view champion and vote in them.

## Champions Collection [/champions]

### List All Championions [GET]

+ Response 200 (application/json)

        [
            {
                "champion": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Champion [POST]

You may create your own Champion using this action. It takes a JSON
object containing a Champion and a collection of champions in the
form of choices.

+ Request (application/json)

        {
            "champion": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /champions/2

    + Body

            {
                "champion": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
