FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Coach

Coach is a simple API allowing consumers to view coach and vote in them.

## Coachs Collection [/coachs]

### List All Coachs [GET]

+ Response 200 (application/json)

        [
            {
                "coach": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Coach [POST]

You may create your own Coach using this action. It takes a JSON
object containing a coach and a collection of coachs in the
form of choices.

+ Request (application/json)

        {
            "coach": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /coachs/2

    + Body

            {
                "coach": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
