FORMAT: 1A
HOST: https://nutrtition.apiblueprint.org/

# Nutrition

Nutrition is a simple API allowing consumers to view food or nutritions and vote in them.

## Nutritions Collection [/nutritions]

### List All Nutritions [GET]

+ Response 200 (application/json)

        [
            {
                "nutrition": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Nutrition [POST]

You may create your own nutrition using this action. It takes a JSON
object containing a nutrition and a collection of food and nutritions in the
form of choices.

+ Request (application/json)

        {
            "nutrition": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /nutritions/2

    + Body

            {
                "nutrition": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
