FORMAT: 1A
HOST: https://stadion.apiblueprint.org/

# Stadion

Stadion is a simple API allowing consumers to view Stadions and vote in them.

## Stadions Collection [/stadions]

### List All Stadiions [GET]

+ Response 200 (application/json)

        [
            {
                "stadion": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Stadion [POST]

You may create your own stadion using this action. It takes a JSON
object containing a stadion and a collection of stadions in the
form of choices.

+ Request (application/json)

        {
            "stadion": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /stadions/2

    + Body

            {
                "stadion": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
