FORMAT: 1A
HOST: https://traditional.apiblueprint.org/

# Traditional

Traditional is a simple API allowing consumers to view traditional sportss and vote in them.

## Tradtitionals Collection [/traditionals]

### List All Traditionals [GET]

+ Response 200 (application/json)

        [
            {
                "traditional": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Traditional [POST]

You may create your own traditional using this action. It takes a JSON
object containing a traditional sport and a collection of traditional sports in the
form of choices.

+ Request (application/json)

        {
            "traditional": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /traditionals/2

    + Body

            {
                "traditional": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
