FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Video

Video is a simple API allowing consumers to view Videos and vote in them.

## Videos Collection [/videos]

### List All Videos [GET]

+ Response 200 (application/json)

        [
            {
                "video": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Video [POST]

You may create your own video using this action. It takes a JSON
object containing a video and a collection of videos in the
form of choices.

+ Request (application/json)

        {
            "video": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /videos/2

    + Body

            {
                "video": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
